openapi: 3.1.0
info:
  title: Product Manager API
  version: 1.0.0
  description: OpenAPI documentation for the Laravel API.
servers:
  - url: /api
    description: Relative API base path

tags:
  - name: Auth
  - name: User
  - name: Apartments
  - name: Apartment Users
  - name: Email Verification

security:
  - bearerAuth: []

paths:
  /login:
    $ref: './paths/auth.yaml#/paths/~1login'
  /register:
    $ref: './paths/auth.yaml#/paths/~1register'
  /logout:
    $ref: './paths/auth.yaml#/paths/~1logout'

  /send-email-verification:
    $ref: './paths/verification.yaml#/paths/~1send-email-verification'
  /verify-email-code:
    $ref: './paths/verification.yaml#/paths/~1verify-email-code'

  /current-user:
    $ref: './paths/user.yaml#/paths/~1current-user'

  /apartments:
    $ref: './paths/apartments.yaml#/paths/~1apartments'
  /apartments/{id}:
    $ref: './paths/apartments.yaml#/paths/~1apartments~1{id}'

  /apartment-users/find-by-email:
    $ref: './paths/apartment-users.yaml#/paths/~1apartment-users~1find-by-email'
  /apartment-users/find-by-phone:
    $ref: './paths/apartment-users.yaml#/paths/~1apartment-users~1find-by-phone'
  /apartment-users:
    $ref: './paths/apartment-users.yaml#/paths/~1apartment-users'
  /apartment-users/{userId}:
    $ref: './paths/apartment-users.yaml#/paths/~1apartment-users~1{userId}'
  /apartment-users/self/disconnect/{apartmentId}:
    $ref: './paths/apartment-users.yaml#/paths/~1apartment-users~1self~1disconnect~1{apartmentId}'

  /categories:
    $ref: './paths/categories.yaml#/paths/~1categories'
  /categories/{id}:
    $ref: './paths/categories.yaml#/paths/~1categories~1{id}'
  /departments:
    $ref: './paths/departments.yaml#/paths/~1departments'
  /departments/{id}:
    $ref: './paths/departments.yaml#/paths/~1departments~1{id}'
  /products:
    $ref: './paths/products.yaml#/paths/~1products'
  /products/{id}:
    $ref: './paths/products.yaml#/paths/~1products~1{id}'

  /currencies:
    $ref: './paths/currencies.yaml#/paths/~1currencies'

  /acquisitions:
    $ref: './paths/acquisitions.yaml#/paths/~1acquisitions'
  /acquisitions/{id}:
    $ref: './paths/acquisitions.yaml#/paths/~1acquisitions~1{id}'
  
  /acquisitions/{acquisitionId}/items:
    $ref: './paths/acquisition-items.yaml#/paths/~1acquisitions~1{acquisitionId}~1items'
  /acquisitions/{acquisitionId}/items/{id}:
    $ref: './paths/acquisition-items.yaml#/paths/~1acquisitions~1{acquisitionId}~1items~1{id}'

  /stock-products:
    $ref: './paths/stock-products.yaml#/paths/~1stock-products'
  /stock-products/{id}:
    $ref: './paths/stock-products.yaml#/paths/~1stock-products~1{id}'

  /archived-acquisition-items:
    $ref: './paths/archived-acquisition-items.yaml#/paths/~1archived-acquisition-items'
  /archived-acquisition-items/{id}:
    $ref: './paths/archived-acquisition-items.yaml#/paths/~1archived-acquisition-items~1{id}'


components:
  $ref: './components.yaml#/components'
